name: make lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    #strategy:
      #matrix:
        #node-version: [8.x, 10.x, 12.x]

    steps:
    - name: pwd
      run: pwd
    - name: install deps
      run: npm install
    - name: run lint
      run: make lint
      #uses: actions/setup-node@v1
      #with:
        #node-version: ${{ matrix.node-version }}
    #- run: make lint
    #- run: npm run build --if-present
    #- run: npm test
     # env:
#        CI: true
