name: make lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    #strategy:
      #matrix:
        #node-version: [8.x, 10.x, 12.x]

    steps:

    - uses: actions/checkout@v2
    - name: import plugin
    - run: npm install eslint-plugin-import    
    - uses: actions/checkout@v2      
    - name: Install airbnb syntax
    - run: npm install eslint-config-airbnb-base
    - uses: actions/checkout@v2      
    - name: ESLint test      
    - run: make lint
      #uses: actions/setup-node@v1
      #with:
        #node-version: ${{ matrix.node-version }}
    #- run: make lint
    #- run: npm run build --if-present
    #- run: npm test
     # env:
#        CI: true
